/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as authAcceptInvitationInvitationIdIndexRouteImport } from './routes/(auth)/accept-invitation/$invitationId/index'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as authLayoutRouteImport } from './routes/(auth)/layout'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as authRegisterRouteImport } from './routes/(auth)/register'
import { Route as authResetPasswordRouteImport } from './routes/(auth)/reset-password'
import { Route as authTwoFactorIndexRouteImport } from './routes/(auth)/two-factor/index'
import { Route as authTwoFactorOtpRouteImport } from './routes/(auth)/two-factor/otp'
import { Route as publicIndexRouteImport } from './routes/(public)/index'
import { Route as DotwellKnownOauthAuthorizationServerRouteImport } from './routes/[.]well-known.oauth-authorization-server'
import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedDashboardAdminIndexRouteImport } from './routes/_authenticated/dashboard/admin/index'
import { Route as AuthenticatedDashboardAdminUsersRouteImport } from './routes/_authenticated/dashboard/admin/users'
import { Route as AuthenticatedDashboardChatIndexRouteImport } from './routes/_authenticated/dashboard/chat/index'
import { Route as AuthenticatedDashboardChatRagRouteImport } from './routes/_authenticated/dashboard/chat/rag'
import { Route as AuthenticatedDashboardChatVercelRouteImport } from './routes/_authenticated/dashboard/chat/vercel'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard/index'
import { Route as AuthenticatedDashboardLayoutRouteImport } from './routes/_authenticated/dashboard/layout'
import { Route as AuthenticatedDashboardProtectExamplesRouteImport } from './routes/_authenticated/dashboard/protect-examples'
import { Route as AuthenticatedDashboardSettingsEnhancedIndexRouteImport } from './routes/_authenticated/dashboard/settings-enhanced/index'
import { Route as AuthenticatedDashboardSettingsIndexRouteImport } from './routes/_authenticated/dashboard/settings/index'
import { Route as AuthenticatedDashboardTanstackDbExampleRouteImport } from './routes/_authenticated/dashboard/tanstack-db-example'
import { Route as AuthenticatedDashboardTelegramChatsRouteImport } from './routes/_authenticated/dashboard/telegram/chats'
import { Route as AuthenticatedDashboardTelegramContactsRouteImport } from './routes/_authenticated/dashboard/telegram/contacts'
import { Route as AuthenticatedDashboardTelegramIndexRouteImport } from './routes/_authenticated/dashboard/telegram/index'
import { Route as AuthenticatedDashboardUpgradeRouteImport } from './routes/_authenticated/dashboard/upgrade'
import { Route as AuthenticatedDashboardWorkspaceIndexRouteImport } from './routes/_authenticated/dashboard/workspace/index'
import { Route as ApiAdminUsersExportRouteImport } from './routes/api/admin/users-export'
import { Route as ApiAdminUsersTableRouteImport } from './routes/api/admin/users-table'
import { Route as ApiAiChatRouteImport } from './routes/api/ai/chat'
import { Route as ApiAiChatImageGenerationRouteImport } from './routes/api/ai/chat.image.generation'
import { Route as ApiAiChatRagRouteImport } from './routes/api/ai/chat.rag'
import { Route as ApiAiMcpTransportRouteImport } from './routes/api/ai/mcp/$transport'
import { Route as ApiAiVercelChatRouteImport } from './routes/api/ai/vercel/chat'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiTelegramChatsTableRouteImport } from './routes/api/telegram/chats-table'
import { Route as ApiTelegramContactsTableRouteImport } from './routes/api/telegram/contacts-table'
import { Route as ApiTelegramTrackOpenRouteImport } from './routes/api/telegram/track-open'
import { Route as ApiTrpcSplatRouteImport } from './routes/api/trpc/$'
import { Route as ApiWebhooksTelegramRouteImport } from './routes/api/webhooks/telegram'
import { Route as TelegramMiniAppIndexRouteImport } from './routes/telegram-mini-app/index'
import { Route as TelegramMiniAppInitDataRouteImport } from './routes/telegram-mini-app/initData'
import { Route as TelegramMiniAppLayoutRouteImport } from './routes/telegram-mini-app/layout'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const TelegramMiniAppLayoutRoute = TelegramMiniAppLayoutRouteImport.update({
  id: '/telegram-mini-app',
  path: '/telegram-mini-app',
  getParentRoute: () => rootRouteImport,
} as any)
const authLayoutRoute = authLayoutRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const TelegramMiniAppIndexRoute = TelegramMiniAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TelegramMiniAppLayoutRoute,
} as any)
const publicIndexRoute = publicIndexRouteImport.update({
  id: '/(public)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TelegramMiniAppInitDataRoute = TelegramMiniAppInitDataRouteImport.update({
  id: '/initData',
  path: '/initData',
  getParentRoute: () => TelegramMiniAppLayoutRoute,
} as any)
const DotwellKnownOauthAuthorizationServerRoute =
  DotwellKnownOauthAuthorizationServerRouteImport.update({
    id: '/.well-known/oauth-authorization-server',
    path: '/.well-known/oauth-authorization-server',
    getParentRoute: () => rootRouteImport,
  } as any)
const authResetPasswordRoute = authResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => authLayoutRoute,
} as any)
const authRegisterRoute = authRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => authLayoutRoute,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authLayoutRoute,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => authLayoutRoute,
} as any)
const AuthenticatedDashboardLayoutRoute =
  AuthenticatedDashboardLayoutRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardLayoutRoute,
  } as any)
const authTwoFactorIndexRoute = authTwoFactorIndexRouteImport.update({
  id: '/two-factor/',
  path: '/two-factor/',
  getParentRoute: () => authLayoutRoute,
} as any)
const ApiWebhooksTelegramRoute = ApiWebhooksTelegramRouteImport.update({
  id: '/api/webhooks/telegram',
  path: '/api/webhooks/telegram',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTelegramTrackOpenRoute = ApiTelegramTrackOpenRouteImport.update({
  id: '/api/telegram/track-open',
  path: '/api/telegram/track-open',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTelegramContactsTableRoute =
  ApiTelegramContactsTableRouteImport.update({
    id: '/api/telegram/contacts-table',
    path: '/api/telegram/contacts-table',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiTelegramChatsTableRoute = ApiTelegramChatsTableRouteImport.update({
  id: '/api/telegram/chats-table',
  path: '/api/telegram/chats-table',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiChatRoute = ApiAiChatRouteImport.update({
  id: '/api/ai/chat',
  path: '/api/ai/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUsersTableRoute = ApiAdminUsersTableRouteImport.update({
  id: '/api/admin/users-table',
  path: '/api/admin/users-table',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUsersExportRoute = ApiAdminUsersExportRouteImport.update({
  id: '/api/admin/users-export',
  path: '/api/admin/users-export',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardUpgradeRoute =
  AuthenticatedDashboardUpgradeRouteImport.update({
    id: '/upgrade',
    path: '/upgrade',
    getParentRoute: () => AuthenticatedDashboardLayoutRoute,
  } as any)
const AuthenticatedDashboardTanstackDbExampleRoute =
  AuthenticatedDashboardTanstackDbExampleRouteImport.update({
    id: '/tanstack-db-example',
    path: '/tanstack-db-example',
    getParentRoute: () => AuthenticatedDashboardLayoutRoute,
  } as any)
const AuthenticatedDashboardProtectExamplesRoute =
  AuthenticatedDashboardProtectExamplesRouteImport.update({
    id: '/protect-examples',
    path: '/protect-examples',
    getParentRoute: () => AuthenticatedDashboardLayoutRoute,
  } as any)
const authTwoFactorOtpRoute = authTwoFactorOtpRouteImport.update({
  id: '/two-factor/otp',
  path: '/two-factor/otp',
  getParentRoute: () => authLayoutRoute,
} as any)
const AuthenticatedDashboardWorkspaceIndexRoute =
  AuthenticatedDashboardWorkspaceIndexRouteImport.update({
    id: '/workspace/',
    path: '/workspace/',
    getParentRoute: () => AuthenticatedDashboardLayoutRoute,
  } as any)
const AuthenticatedDashboardTelegramIndexRoute =
  AuthenticatedDashboardTelegramIndexRouteImport.update({
    id: '/telegram/',
    path: '/telegram/',
    getParentRoute: () => AuthenticatedDashboardLayoutRoute,
  } as any)
const AuthenticatedDashboardSettingsIndexRoute =
  AuthenticatedDashboardSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedDashboardLayoutRoute,
  } as any)
const AuthenticatedDashboardSettingsEnhancedIndexRoute =
  AuthenticatedDashboardSettingsEnhancedIndexRouteImport.update({
    id: '/settings-enhanced/',
    path: '/settings-enhanced/',
    getParentRoute: () => AuthenticatedDashboardLayoutRoute,
  } as any)
const AuthenticatedDashboardChatIndexRoute =
  AuthenticatedDashboardChatIndexRouteImport.update({
    id: '/chat/',
    path: '/chat/',
    getParentRoute: () => AuthenticatedDashboardLayoutRoute,
  } as any)
const AuthenticatedDashboardAdminIndexRoute =
  AuthenticatedDashboardAdminIndexRouteImport.update({
    id: '/admin/',
    path: '/admin/',
    getParentRoute: () => AuthenticatedDashboardLayoutRoute,
  } as any)
const authAcceptInvitationInvitationIdIndexRoute =
  authAcceptInvitationInvitationIdIndexRouteImport.update({
    id: '/accept-invitation/$invitationId/',
    path: '/accept-invitation/$invitationId/',
    getParentRoute: () => authLayoutRoute,
  } as any)
const ApiAiVercelChatRoute = ApiAiVercelChatRouteImport.update({
  id: '/api/ai/vercel/chat',
  path: '/api/ai/vercel/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiMcpTransportRoute = ApiAiMcpTransportRouteImport.update({
  id: '/api/ai/mcp/$transport',
  path: '/api/ai/mcp/$transport',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiChatRagRoute = ApiAiChatRagRouteImport.update({
  id: '/rag',
  path: '/rag',
  getParentRoute: () => ApiAiChatRoute,
} as any)
const AuthenticatedDashboardTelegramContactsRoute =
  AuthenticatedDashboardTelegramContactsRouteImport.update({
    id: '/telegram/contacts',
    path: '/telegram/contacts',
    getParentRoute: () => AuthenticatedDashboardLayoutRoute,
  } as any)
const AuthenticatedDashboardTelegramChatsRoute =
  AuthenticatedDashboardTelegramChatsRouteImport.update({
    id: '/telegram/chats',
    path: '/telegram/chats',
    getParentRoute: () => AuthenticatedDashboardLayoutRoute,
  } as any)
const AuthenticatedDashboardChatVercelRoute =
  AuthenticatedDashboardChatVercelRouteImport.update({
    id: '/chat/vercel',
    path: '/chat/vercel',
    getParentRoute: () => AuthenticatedDashboardLayoutRoute,
  } as any)
const AuthenticatedDashboardChatRagRoute =
  AuthenticatedDashboardChatRagRouteImport.update({
    id: '/chat/rag',
    path: '/chat/rag',
    getParentRoute: () => AuthenticatedDashboardLayoutRoute,
  } as any)
const AuthenticatedDashboardAdminUsersRoute =
  AuthenticatedDashboardAdminUsersRouteImport.update({
    id: '/admin/users',
    path: '/admin/users',
    getParentRoute: () => AuthenticatedDashboardLayoutRoute,
  } as any)
const ApiAiChatImageGenerationRoute =
  ApiAiChatImageGenerationRouteImport.update({
    id: '/image/generation',
    path: '/image/generation',
    getParentRoute: () => ApiAiChatRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/telegram-mini-app': typeof TelegramMiniAppLayoutRouteWithChildren
  '/': typeof publicIndexRoute
  '/dashboard': typeof AuthenticatedDashboardLayoutRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/reset-password': typeof authResetPasswordRoute
  '/.well-known/oauth-authorization-server': typeof DotwellKnownOauthAuthorizationServerRoute
  '/telegram-mini-app/initData': typeof TelegramMiniAppInitDataRoute
  '/telegram-mini-app/': typeof TelegramMiniAppIndexRoute
  '/two-factor/otp': typeof authTwoFactorOtpRoute
  '/dashboard/protect-examples': typeof AuthenticatedDashboardProtectExamplesRoute
  '/dashboard/tanstack-db-example': typeof AuthenticatedDashboardTanstackDbExampleRoute
  '/dashboard/upgrade': typeof AuthenticatedDashboardUpgradeRoute
  '/api/admin/users-export': typeof ApiAdminUsersExportRoute
  '/api/admin/users-table': typeof ApiAdminUsersTableRoute
  '/api/ai/chat': typeof ApiAiChatRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/telegram/chats-table': typeof ApiTelegramChatsTableRoute
  '/api/telegram/contacts-table': typeof ApiTelegramContactsTableRoute
  '/api/telegram/track-open': typeof ApiTelegramTrackOpenRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/api/webhooks/telegram': typeof ApiWebhooksTelegramRoute
  '/two-factor/': typeof authTwoFactorIndexRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/admin/users': typeof AuthenticatedDashboardAdminUsersRoute
  '/dashboard/chat/rag': typeof AuthenticatedDashboardChatRagRoute
  '/dashboard/chat/vercel': typeof AuthenticatedDashboardChatVercelRoute
  '/dashboard/telegram/chats': typeof AuthenticatedDashboardTelegramChatsRoute
  '/dashboard/telegram/contacts': typeof AuthenticatedDashboardTelegramContactsRoute
  '/api/ai/chat/rag': typeof ApiAiChatRagRoute
  '/api/ai/mcp/$transport': typeof ApiAiMcpTransportRoute
  '/api/ai/vercel/chat': typeof ApiAiVercelChatRoute
  '/accept-invitation/$invitationId/': typeof authAcceptInvitationInvitationIdIndexRoute
  '/dashboard/admin/': typeof AuthenticatedDashboardAdminIndexRoute
  '/dashboard/chat/': typeof AuthenticatedDashboardChatIndexRoute
  '/dashboard/settings-enhanced/': typeof AuthenticatedDashboardSettingsEnhancedIndexRoute
  '/dashboard/settings/': typeof AuthenticatedDashboardSettingsIndexRoute
  '/dashboard/telegram/': typeof AuthenticatedDashboardTelegramIndexRoute
  '/dashboard/workspace/': typeof AuthenticatedDashboardWorkspaceIndexRoute
  '/api/ai/chat/image/generation': typeof ApiAiChatImageGenerationRoute
}
export interface FileRoutesByTo {
  '/': typeof publicIndexRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/reset-password': typeof authResetPasswordRoute
  '/.well-known/oauth-authorization-server': typeof DotwellKnownOauthAuthorizationServerRoute
  '/telegram-mini-app/initData': typeof TelegramMiniAppInitDataRoute
  '/telegram-mini-app': typeof TelegramMiniAppIndexRoute
  '/two-factor/otp': typeof authTwoFactorOtpRoute
  '/dashboard/protect-examples': typeof AuthenticatedDashboardProtectExamplesRoute
  '/dashboard/tanstack-db-example': typeof AuthenticatedDashboardTanstackDbExampleRoute
  '/dashboard/upgrade': typeof AuthenticatedDashboardUpgradeRoute
  '/api/admin/users-export': typeof ApiAdminUsersExportRoute
  '/api/admin/users-table': typeof ApiAdminUsersTableRoute
  '/api/ai/chat': typeof ApiAiChatRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/telegram/chats-table': typeof ApiTelegramChatsTableRoute
  '/api/telegram/contacts-table': typeof ApiTelegramContactsTableRoute
  '/api/telegram/track-open': typeof ApiTelegramTrackOpenRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/api/webhooks/telegram': typeof ApiWebhooksTelegramRoute
  '/two-factor': typeof authTwoFactorIndexRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/admin/users': typeof AuthenticatedDashboardAdminUsersRoute
  '/dashboard/chat/rag': typeof AuthenticatedDashboardChatRagRoute
  '/dashboard/chat/vercel': typeof AuthenticatedDashboardChatVercelRoute
  '/dashboard/telegram/chats': typeof AuthenticatedDashboardTelegramChatsRoute
  '/dashboard/telegram/contacts': typeof AuthenticatedDashboardTelegramContactsRoute
  '/api/ai/chat/rag': typeof ApiAiChatRagRoute
  '/api/ai/mcp/$transport': typeof ApiAiMcpTransportRoute
  '/api/ai/vercel/chat': typeof ApiAiVercelChatRoute
  '/accept-invitation/$invitationId': typeof authAcceptInvitationInvitationIdIndexRoute
  '/dashboard/admin': typeof AuthenticatedDashboardAdminIndexRoute
  '/dashboard/chat': typeof AuthenticatedDashboardChatIndexRoute
  '/dashboard/settings-enhanced': typeof AuthenticatedDashboardSettingsEnhancedIndexRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsIndexRoute
  '/dashboard/telegram': typeof AuthenticatedDashboardTelegramIndexRoute
  '/dashboard/workspace': typeof AuthenticatedDashboardWorkspaceIndexRoute
  '/api/ai/chat/image/generation': typeof ApiAiChatImageGenerationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(auth)': typeof authLayoutRouteWithChildren
  '/telegram-mini-app': typeof TelegramMiniAppLayoutRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardLayoutRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/register': typeof authRegisterRoute
  '/(auth)/reset-password': typeof authResetPasswordRoute
  '/.well-known/oauth-authorization-server': typeof DotwellKnownOauthAuthorizationServerRoute
  '/telegram-mini-app/initData': typeof TelegramMiniAppInitDataRoute
  '/(public)/': typeof publicIndexRoute
  '/telegram-mini-app/': typeof TelegramMiniAppIndexRoute
  '/(auth)/two-factor/otp': typeof authTwoFactorOtpRoute
  '/_authenticated/dashboard/protect-examples': typeof AuthenticatedDashboardProtectExamplesRoute
  '/_authenticated/dashboard/tanstack-db-example': typeof AuthenticatedDashboardTanstackDbExampleRoute
  '/_authenticated/dashboard/upgrade': typeof AuthenticatedDashboardUpgradeRoute
  '/api/admin/users-export': typeof ApiAdminUsersExportRoute
  '/api/admin/users-table': typeof ApiAdminUsersTableRoute
  '/api/ai/chat': typeof ApiAiChatRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/telegram/chats-table': typeof ApiTelegramChatsTableRoute
  '/api/telegram/contacts-table': typeof ApiTelegramContactsTableRoute
  '/api/telegram/track-open': typeof ApiTelegramTrackOpenRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/api/webhooks/telegram': typeof ApiWebhooksTelegramRoute
  '/(auth)/two-factor/': typeof authTwoFactorIndexRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/dashboard/admin/users': typeof AuthenticatedDashboardAdminUsersRoute
  '/_authenticated/dashboard/chat/rag': typeof AuthenticatedDashboardChatRagRoute
  '/_authenticated/dashboard/chat/vercel': typeof AuthenticatedDashboardChatVercelRoute
  '/_authenticated/dashboard/telegram/chats': typeof AuthenticatedDashboardTelegramChatsRoute
  '/_authenticated/dashboard/telegram/contacts': typeof AuthenticatedDashboardTelegramContactsRoute
  '/api/ai/chat/rag': typeof ApiAiChatRagRoute
  '/api/ai/mcp/$transport': typeof ApiAiMcpTransportRoute
  '/api/ai/vercel/chat': typeof ApiAiVercelChatRoute
  '/(auth)/accept-invitation/$invitationId/': typeof authAcceptInvitationInvitationIdIndexRoute
  '/_authenticated/dashboard/admin/': typeof AuthenticatedDashboardAdminIndexRoute
  '/_authenticated/dashboard/chat/': typeof AuthenticatedDashboardChatIndexRoute
  '/_authenticated/dashboard/settings-enhanced/': typeof AuthenticatedDashboardSettingsEnhancedIndexRoute
  '/_authenticated/dashboard/settings/': typeof AuthenticatedDashboardSettingsIndexRoute
  '/_authenticated/dashboard/telegram/': typeof AuthenticatedDashboardTelegramIndexRoute
  '/_authenticated/dashboard/workspace/': typeof AuthenticatedDashboardWorkspaceIndexRoute
  '/api/ai/chat/image/generation': typeof ApiAiChatImageGenerationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/telegram-mini-app'
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/.well-known/oauth-authorization-server'
    | '/telegram-mini-app/initData'
    | '/telegram-mini-app/'
    | '/two-factor/otp'
    | '/dashboard/protect-examples'
    | '/dashboard/tanstack-db-example'
    | '/dashboard/upgrade'
    | '/api/admin/users-export'
    | '/api/admin/users-table'
    | '/api/ai/chat'
    | '/api/auth/$'
    | '/api/telegram/chats-table'
    | '/api/telegram/contacts-table'
    | '/api/telegram/track-open'
    | '/api/trpc/$'
    | '/api/webhooks/telegram'
    | '/two-factor/'
    | '/dashboard/'
    | '/dashboard/admin/users'
    | '/dashboard/chat/rag'
    | '/dashboard/chat/vercel'
    | '/dashboard/telegram/chats'
    | '/dashboard/telegram/contacts'
    | '/api/ai/chat/rag'
    | '/api/ai/mcp/$transport'
    | '/api/ai/vercel/chat'
    | '/accept-invitation/$invitationId/'
    | '/dashboard/admin/'
    | '/dashboard/chat/'
    | '/dashboard/settings-enhanced/'
    | '/dashboard/settings/'
    | '/dashboard/telegram/'
    | '/dashboard/workspace/'
    | '/api/ai/chat/image/generation'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/.well-known/oauth-authorization-server'
    | '/telegram-mini-app/initData'
    | '/telegram-mini-app'
    | '/two-factor/otp'
    | '/dashboard/protect-examples'
    | '/dashboard/tanstack-db-example'
    | '/dashboard/upgrade'
    | '/api/admin/users-export'
    | '/api/admin/users-table'
    | '/api/ai/chat'
    | '/api/auth/$'
    | '/api/telegram/chats-table'
    | '/api/telegram/contacts-table'
    | '/api/telegram/track-open'
    | '/api/trpc/$'
    | '/api/webhooks/telegram'
    | '/two-factor'
    | '/dashboard'
    | '/dashboard/admin/users'
    | '/dashboard/chat/rag'
    | '/dashboard/chat/vercel'
    | '/dashboard/telegram/chats'
    | '/dashboard/telegram/contacts'
    | '/api/ai/chat/rag'
    | '/api/ai/mcp/$transport'
    | '/api/ai/vercel/chat'
    | '/accept-invitation/$invitationId'
    | '/dashboard/admin'
    | '/dashboard/chat'
    | '/dashboard/settings-enhanced'
    | '/dashboard/settings'
    | '/dashboard/telegram'
    | '/dashboard/workspace'
    | '/api/ai/chat/image/generation'
  id:
    | '__root__'
    | '/(auth)'
    | '/telegram-mini-app'
    | '/_authenticated'
    | '/_authenticated/dashboard'
    | '/(auth)/forgot-password'
    | '/(auth)/login'
    | '/(auth)/register'
    | '/(auth)/reset-password'
    | '/.well-known/oauth-authorization-server'
    | '/telegram-mini-app/initData'
    | '/(public)/'
    | '/telegram-mini-app/'
    | '/(auth)/two-factor/otp'
    | '/_authenticated/dashboard/protect-examples'
    | '/_authenticated/dashboard/tanstack-db-example'
    | '/_authenticated/dashboard/upgrade'
    | '/api/admin/users-export'
    | '/api/admin/users-table'
    | '/api/ai/chat'
    | '/api/auth/$'
    | '/api/telegram/chats-table'
    | '/api/telegram/contacts-table'
    | '/api/telegram/track-open'
    | '/api/trpc/$'
    | '/api/webhooks/telegram'
    | '/(auth)/two-factor/'
    | '/_authenticated/dashboard/'
    | '/_authenticated/dashboard/admin/users'
    | '/_authenticated/dashboard/chat/rag'
    | '/_authenticated/dashboard/chat/vercel'
    | '/_authenticated/dashboard/telegram/chats'
    | '/_authenticated/dashboard/telegram/contacts'
    | '/api/ai/chat/rag'
    | '/api/ai/mcp/$transport'
    | '/api/ai/vercel/chat'
    | '/(auth)/accept-invitation/$invitationId/'
    | '/_authenticated/dashboard/admin/'
    | '/_authenticated/dashboard/chat/'
    | '/_authenticated/dashboard/settings-enhanced/'
    | '/_authenticated/dashboard/settings/'
    | '/_authenticated/dashboard/telegram/'
    | '/_authenticated/dashboard/workspace/'
    | '/api/ai/chat/image/generation'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authLayoutRoute: typeof authLayoutRouteWithChildren
  TelegramMiniAppLayoutRoute: typeof TelegramMiniAppLayoutRouteWithChildren
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  DotwellKnownOauthAuthorizationServerRoute: typeof DotwellKnownOauthAuthorizationServerRoute
  publicIndexRoute: typeof publicIndexRoute
  ApiAdminUsersExportRoute: typeof ApiAdminUsersExportRoute
  ApiAdminUsersTableRoute: typeof ApiAdminUsersTableRoute
  ApiAiChatRoute: typeof ApiAiChatRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiTelegramChatsTableRoute: typeof ApiTelegramChatsTableRoute
  ApiTelegramContactsTableRoute: typeof ApiTelegramContactsTableRoute
  ApiTelegramTrackOpenRoute: typeof ApiTelegramTrackOpenRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
  ApiWebhooksTelegramRoute: typeof ApiWebhooksTelegramRoute
  ApiAiMcpTransportRoute: typeof ApiAiMcpTransportRoute
  ApiAiVercelChatRoute: typeof ApiAiVercelChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/telegram-mini-app': {
      id: '/telegram-mini-app'
      path: '/telegram-mini-app'
      fullPath: '/telegram-mini-app'
      preLoaderRoute: typeof TelegramMiniAppLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/telegram-mini-app/': {
      id: '/telegram-mini-app/'
      path: '/'
      fullPath: '/telegram-mini-app/'
      preLoaderRoute: typeof TelegramMiniAppIndexRouteImport
      parentRoute: typeof TelegramMiniAppLayoutRoute
    }
    '/(public)/': {
      id: '/(public)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/telegram-mini-app/initData': {
      id: '/telegram-mini-app/initData'
      path: '/initData'
      fullPath: '/telegram-mini-app/initData'
      preLoaderRoute: typeof TelegramMiniAppInitDataRouteImport
      parentRoute: typeof TelegramMiniAppLayoutRoute
    }
    '/.well-known/oauth-authorization-server': {
      id: '/.well-known/oauth-authorization-server'
      path: '/.well-known/oauth-authorization-server'
      fullPath: '/.well-known/oauth-authorization-server'
      preLoaderRoute: typeof DotwellKnownOauthAuthorizationServerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/reset-password': {
      id: '/(auth)/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof authResetPasswordRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/(auth)/register': {
      id: '/(auth)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardLayoutRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardLayoutRoute
    }
    '/(auth)/two-factor/': {
      id: '/(auth)/two-factor/'
      path: '/two-factor'
      fullPath: '/two-factor/'
      preLoaderRoute: typeof authTwoFactorIndexRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/api/webhooks/telegram': {
      id: '/api/webhooks/telegram'
      path: '/api/webhooks/telegram'
      fullPath: '/api/webhooks/telegram'
      preLoaderRoute: typeof ApiWebhooksTelegramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/telegram/track-open': {
      id: '/api/telegram/track-open'
      path: '/api/telegram/track-open'
      fullPath: '/api/telegram/track-open'
      preLoaderRoute: typeof ApiTelegramTrackOpenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/telegram/contacts-table': {
      id: '/api/telegram/contacts-table'
      path: '/api/telegram/contacts-table'
      fullPath: '/api/telegram/contacts-table'
      preLoaderRoute: typeof ApiTelegramContactsTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/telegram/chats-table': {
      id: '/api/telegram/chats-table'
      path: '/api/telegram/chats-table'
      fullPath: '/api/telegram/chats-table'
      preLoaderRoute: typeof ApiTelegramChatsTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/chat': {
      id: '/api/ai/chat'
      path: '/api/ai/chat'
      fullPath: '/api/ai/chat'
      preLoaderRoute: typeof ApiAiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/users-table': {
      id: '/api/admin/users-table'
      path: '/api/admin/users-table'
      fullPath: '/api/admin/users-table'
      preLoaderRoute: typeof ApiAdminUsersTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/users-export': {
      id: '/api/admin/users-export'
      path: '/api/admin/users-export'
      fullPath: '/api/admin/users-export'
      preLoaderRoute: typeof ApiAdminUsersExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard/upgrade': {
      id: '/_authenticated/dashboard/upgrade'
      path: '/upgrade'
      fullPath: '/dashboard/upgrade'
      preLoaderRoute: typeof AuthenticatedDashboardUpgradeRouteImport
      parentRoute: typeof AuthenticatedDashboardLayoutRoute
    }
    '/_authenticated/dashboard/tanstack-db-example': {
      id: '/_authenticated/dashboard/tanstack-db-example'
      path: '/tanstack-db-example'
      fullPath: '/dashboard/tanstack-db-example'
      preLoaderRoute: typeof AuthenticatedDashboardTanstackDbExampleRouteImport
      parentRoute: typeof AuthenticatedDashboardLayoutRoute
    }
    '/_authenticated/dashboard/protect-examples': {
      id: '/_authenticated/dashboard/protect-examples'
      path: '/protect-examples'
      fullPath: '/dashboard/protect-examples'
      preLoaderRoute: typeof AuthenticatedDashboardProtectExamplesRouteImport
      parentRoute: typeof AuthenticatedDashboardLayoutRoute
    }
    '/(auth)/two-factor/otp': {
      id: '/(auth)/two-factor/otp'
      path: '/two-factor/otp'
      fullPath: '/two-factor/otp'
      preLoaderRoute: typeof authTwoFactorOtpRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/_authenticated/dashboard/workspace/': {
      id: '/_authenticated/dashboard/workspace/'
      path: '/workspace'
      fullPath: '/dashboard/workspace/'
      preLoaderRoute: typeof AuthenticatedDashboardWorkspaceIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardLayoutRoute
    }
    '/_authenticated/dashboard/telegram/': {
      id: '/_authenticated/dashboard/telegram/'
      path: '/telegram'
      fullPath: '/dashboard/telegram/'
      preLoaderRoute: typeof AuthenticatedDashboardTelegramIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardLayoutRoute
    }
    '/_authenticated/dashboard/settings/': {
      id: '/_authenticated/dashboard/settings/'
      path: '/settings'
      fullPath: '/dashboard/settings/'
      preLoaderRoute: typeof AuthenticatedDashboardSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardLayoutRoute
    }
    '/_authenticated/dashboard/settings-enhanced/': {
      id: '/_authenticated/dashboard/settings-enhanced/'
      path: '/settings-enhanced'
      fullPath: '/dashboard/settings-enhanced/'
      preLoaderRoute: typeof AuthenticatedDashboardSettingsEnhancedIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardLayoutRoute
    }
    '/_authenticated/dashboard/chat/': {
      id: '/_authenticated/dashboard/chat/'
      path: '/chat'
      fullPath: '/dashboard/chat/'
      preLoaderRoute: typeof AuthenticatedDashboardChatIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardLayoutRoute
    }
    '/_authenticated/dashboard/admin/': {
      id: '/_authenticated/dashboard/admin/'
      path: '/admin'
      fullPath: '/dashboard/admin/'
      preLoaderRoute: typeof AuthenticatedDashboardAdminIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardLayoutRoute
    }
    '/(auth)/accept-invitation/$invitationId/': {
      id: '/(auth)/accept-invitation/$invitationId/'
      path: '/accept-invitation/$invitationId'
      fullPath: '/accept-invitation/$invitationId/'
      preLoaderRoute: typeof authAcceptInvitationInvitationIdIndexRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/api/ai/vercel/chat': {
      id: '/api/ai/vercel/chat'
      path: '/api/ai/vercel/chat'
      fullPath: '/api/ai/vercel/chat'
      preLoaderRoute: typeof ApiAiVercelChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/mcp/$transport': {
      id: '/api/ai/mcp/$transport'
      path: '/api/ai/mcp/$transport'
      fullPath: '/api/ai/mcp/$transport'
      preLoaderRoute: typeof ApiAiMcpTransportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/chat/rag': {
      id: '/api/ai/chat/rag'
      path: '/rag'
      fullPath: '/api/ai/chat/rag'
      preLoaderRoute: typeof ApiAiChatRagRouteImport
      parentRoute: typeof ApiAiChatRoute
    }
    '/_authenticated/dashboard/telegram/contacts': {
      id: '/_authenticated/dashboard/telegram/contacts'
      path: '/telegram/contacts'
      fullPath: '/dashboard/telegram/contacts'
      preLoaderRoute: typeof AuthenticatedDashboardTelegramContactsRouteImport
      parentRoute: typeof AuthenticatedDashboardLayoutRoute
    }
    '/_authenticated/dashboard/telegram/chats': {
      id: '/_authenticated/dashboard/telegram/chats'
      path: '/telegram/chats'
      fullPath: '/dashboard/telegram/chats'
      preLoaderRoute: typeof AuthenticatedDashboardTelegramChatsRouteImport
      parentRoute: typeof AuthenticatedDashboardLayoutRoute
    }
    '/_authenticated/dashboard/chat/vercel': {
      id: '/_authenticated/dashboard/chat/vercel'
      path: '/chat/vercel'
      fullPath: '/dashboard/chat/vercel'
      preLoaderRoute: typeof AuthenticatedDashboardChatVercelRouteImport
      parentRoute: typeof AuthenticatedDashboardLayoutRoute
    }
    '/_authenticated/dashboard/chat/rag': {
      id: '/_authenticated/dashboard/chat/rag'
      path: '/chat/rag'
      fullPath: '/dashboard/chat/rag'
      preLoaderRoute: typeof AuthenticatedDashboardChatRagRouteImport
      parentRoute: typeof AuthenticatedDashboardLayoutRoute
    }
    '/_authenticated/dashboard/admin/users': {
      id: '/_authenticated/dashboard/admin/users'
      path: '/admin/users'
      fullPath: '/dashboard/admin/users'
      preLoaderRoute: typeof AuthenticatedDashboardAdminUsersRouteImport
      parentRoute: typeof AuthenticatedDashboardLayoutRoute
    }
    '/api/ai/chat/image/generation': {
      id: '/api/ai/chat/image/generation'
      path: '/image/generation'
      fullPath: '/api/ai/chat/image/generation'
      preLoaderRoute: typeof ApiAiChatImageGenerationRouteImport
      parentRoute: typeof ApiAiChatRoute
    }
  }
}

interface authLayoutRouteChildren {
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authLoginRoute: typeof authLoginRoute
  authRegisterRoute: typeof authRegisterRoute
  authResetPasswordRoute: typeof authResetPasswordRoute
  authTwoFactorOtpRoute: typeof authTwoFactorOtpRoute
  authTwoFactorIndexRoute: typeof authTwoFactorIndexRoute
  authAcceptInvitationInvitationIdIndexRoute: typeof authAcceptInvitationInvitationIdIndexRoute
}

const authLayoutRouteChildren: authLayoutRouteChildren = {
  authForgotPasswordRoute: authForgotPasswordRoute,
  authLoginRoute: authLoginRoute,
  authRegisterRoute: authRegisterRoute,
  authResetPasswordRoute: authResetPasswordRoute,
  authTwoFactorOtpRoute: authTwoFactorOtpRoute,
  authTwoFactorIndexRoute: authTwoFactorIndexRoute,
  authAcceptInvitationInvitationIdIndexRoute:
    authAcceptInvitationInvitationIdIndexRoute,
}

const authLayoutRouteWithChildren = authLayoutRoute._addFileChildren(
  authLayoutRouteChildren,
)

interface TelegramMiniAppLayoutRouteChildren {
  TelegramMiniAppInitDataRoute: typeof TelegramMiniAppInitDataRoute
  TelegramMiniAppIndexRoute: typeof TelegramMiniAppIndexRoute
}

const TelegramMiniAppLayoutRouteChildren: TelegramMiniAppLayoutRouteChildren = {
  TelegramMiniAppInitDataRoute: TelegramMiniAppInitDataRoute,
  TelegramMiniAppIndexRoute: TelegramMiniAppIndexRoute,
}

const TelegramMiniAppLayoutRouteWithChildren =
  TelegramMiniAppLayoutRoute._addFileChildren(
    TelegramMiniAppLayoutRouteChildren,
  )

interface AuthenticatedDashboardLayoutRouteChildren {
  AuthenticatedDashboardProtectExamplesRoute: typeof AuthenticatedDashboardProtectExamplesRoute
  AuthenticatedDashboardTanstackDbExampleRoute: typeof AuthenticatedDashboardTanstackDbExampleRoute
  AuthenticatedDashboardUpgradeRoute: typeof AuthenticatedDashboardUpgradeRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedDashboardAdminUsersRoute: typeof AuthenticatedDashboardAdminUsersRoute
  AuthenticatedDashboardChatRagRoute: typeof AuthenticatedDashboardChatRagRoute
  AuthenticatedDashboardChatVercelRoute: typeof AuthenticatedDashboardChatVercelRoute
  AuthenticatedDashboardTelegramChatsRoute: typeof AuthenticatedDashboardTelegramChatsRoute
  AuthenticatedDashboardTelegramContactsRoute: typeof AuthenticatedDashboardTelegramContactsRoute
  AuthenticatedDashboardAdminIndexRoute: typeof AuthenticatedDashboardAdminIndexRoute
  AuthenticatedDashboardChatIndexRoute: typeof AuthenticatedDashboardChatIndexRoute
  AuthenticatedDashboardSettingsEnhancedIndexRoute: typeof AuthenticatedDashboardSettingsEnhancedIndexRoute
  AuthenticatedDashboardSettingsIndexRoute: typeof AuthenticatedDashboardSettingsIndexRoute
  AuthenticatedDashboardTelegramIndexRoute: typeof AuthenticatedDashboardTelegramIndexRoute
  AuthenticatedDashboardWorkspaceIndexRoute: typeof AuthenticatedDashboardWorkspaceIndexRoute
}

const AuthenticatedDashboardLayoutRouteChildren: AuthenticatedDashboardLayoutRouteChildren =
  {
    AuthenticatedDashboardProtectExamplesRoute:
      AuthenticatedDashboardProtectExamplesRoute,
    AuthenticatedDashboardTanstackDbExampleRoute:
      AuthenticatedDashboardTanstackDbExampleRoute,
    AuthenticatedDashboardUpgradeRoute: AuthenticatedDashboardUpgradeRoute,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
    AuthenticatedDashboardAdminUsersRoute:
      AuthenticatedDashboardAdminUsersRoute,
    AuthenticatedDashboardChatRagRoute: AuthenticatedDashboardChatRagRoute,
    AuthenticatedDashboardChatVercelRoute:
      AuthenticatedDashboardChatVercelRoute,
    AuthenticatedDashboardTelegramChatsRoute:
      AuthenticatedDashboardTelegramChatsRoute,
    AuthenticatedDashboardTelegramContactsRoute:
      AuthenticatedDashboardTelegramContactsRoute,
    AuthenticatedDashboardAdminIndexRoute:
      AuthenticatedDashboardAdminIndexRoute,
    AuthenticatedDashboardChatIndexRoute: AuthenticatedDashboardChatIndexRoute,
    AuthenticatedDashboardSettingsEnhancedIndexRoute:
      AuthenticatedDashboardSettingsEnhancedIndexRoute,
    AuthenticatedDashboardSettingsIndexRoute:
      AuthenticatedDashboardSettingsIndexRoute,
    AuthenticatedDashboardTelegramIndexRoute:
      AuthenticatedDashboardTelegramIndexRoute,
    AuthenticatedDashboardWorkspaceIndexRoute:
      AuthenticatedDashboardWorkspaceIndexRoute,
  }

const AuthenticatedDashboardLayoutRouteWithChildren =
  AuthenticatedDashboardLayoutRoute._addFileChildren(
    AuthenticatedDashboardLayoutRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardLayoutRoute: typeof AuthenticatedDashboardLayoutRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardLayoutRoute:
    AuthenticatedDashboardLayoutRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface ApiAiChatRouteChildren {
  ApiAiChatRagRoute: typeof ApiAiChatRagRoute
  ApiAiChatImageGenerationRoute: typeof ApiAiChatImageGenerationRoute
}

const ApiAiChatRouteChildren: ApiAiChatRouteChildren = {
  ApiAiChatRagRoute: ApiAiChatRagRoute,
  ApiAiChatImageGenerationRoute: ApiAiChatImageGenerationRoute,
}

const ApiAiChatRouteWithChildren = ApiAiChatRoute._addFileChildren(
  ApiAiChatRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  authLayoutRoute: authLayoutRouteWithChildren,
  TelegramMiniAppLayoutRoute: TelegramMiniAppLayoutRouteWithChildren,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  DotwellKnownOauthAuthorizationServerRoute:
    DotwellKnownOauthAuthorizationServerRoute,
  publicIndexRoute: publicIndexRoute,
  ApiAdminUsersExportRoute: ApiAdminUsersExportRoute,
  ApiAdminUsersTableRoute: ApiAdminUsersTableRoute,
  ApiAiChatRoute: ApiAiChatRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiTelegramChatsTableRoute: ApiTelegramChatsTableRoute,
  ApiTelegramContactsTableRoute: ApiTelegramContactsTableRoute,
  ApiTelegramTrackOpenRoute: ApiTelegramTrackOpenRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
  ApiWebhooksTelegramRoute: ApiWebhooksTelegramRoute,
  ApiAiMcpTransportRoute: ApiAiMcpTransportRoute,
  ApiAiVercelChatRoute: ApiAiVercelChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.tsx'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
